/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bussinesLogic.LoginController;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandru
 */
public class LoginForm extends javax.swing.JFrame {

    private LoginController loginController ;
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents(); 
        loginController = new LoginController ();
     //   passwordField_login_password.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lable_login_username = new javax.swing.JLabel();
        lable_login_password = new javax.swing.JLabel();
        textField_login_username = new javax.swing.JTextField();
        button_login = new javax.swing.JButton();
        passwordField_login_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lable_login_username.setText("Nume Utilizator :");

        lable_login_password.setText("Parola :");

        textField_login_username.setText("bratu");

        button_login.setText("Intra in Aplicatie");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });

        passwordField_login_password.setText("bratu323");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lable_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lable_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordField_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textField_login_username, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lable_login_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lable_login_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(button_login, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        passwordField_login_password.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed
        // TODO add your handling code here:
        String username;
        String password;
        int result ;
        username = textField_login_username.getText();
        password = passwordField_login_password.getText();
        //password = passwordField_login_password.getPassword().toString();
        
        if ( username.length() > 0 && password.length() > 0 ) {
           result =  loginController.login ( username , password );
           if ( result == -1 )
           {
               String message="Eroare! Nume de utilizator si/sau parola gresite!!!";
               JOptionPane.showMessageDialog((Component) null,message,"Date introduse gresit!!!",JOptionPane.CANCEL_OPTION);
           }
           else
           {
               if (result ==  1)
               {
                   RegularUserForm regularUserForm = new RegularUserForm ();
                   regularUserForm.setVisible(true);
                   this.setVisible(false);
               }
               else
               {
                   if (result == 2)
                   {
                       String message="Interfata administrator in lucru!!!";
                       JOptionPane.showMessageDialog((Component) null,message,"Admin!!!",JOptionPane.CANCEL_OPTION);
           
                   }
               }
           }
        }
        else {
            String message="Eroare! Va rugam anuntati un administrator!!!";
            if ( username.length() == 0 && password.length() == 0) {
                message="Introduceti un Nume de Utilizator si o Parola !!!";
            }
            else {
                if ( username.length() ==0 ) {
                    message="Introduceti un Nume de Utilizator !!!";
                }
                else {
                    if ( password.length() == 0 ) {
                        message="Introduceti o Parola !!!";               
                    }
                }
            }
            JOptionPane.showMessageDialog((Component) null,message,"Lipsa Date!!!",JOptionPane.CANCEL_OPTION);            
        }            
    }//GEN-LAST:event_button_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login;
    private javax.swing.JLabel lable_login_password;
    private javax.swing.JLabel lable_login_username;
    private javax.swing.JPasswordField passwordField_login_password;
    private javax.swing.JTextField textField_login_username;
    // End of variables declaration//GEN-END:variables
}
